; WYSYŁKA SZEREGOWA  3-CH KOLEJNYCH KOMUNIKATÓW MIN 20 ZNAKÓW NA MODUŁ LCD
;
; USTAWIENIA:
;  - CZĘSTOTLIWOŚĆ ZEGARA: 12MHZ
;  - CZĘSTOTLIWOŚĆ ODŚWIEŻANIA: 50000X



; NAZYWANIE PINOW
D7 EQU P1.7
D6 EQU P1.6
D5 EQU P1.5
D4 EQU P1.4
RS EQU P1.3
E  EQU P1.2

; PROGRAM GLOWNY
CALL USTAW_CZASOMIERZE
CALL USTAW_LCD

CALL CZYSZCZENIE
CALL DLUGI_KOMUNIKAT_1
CALL WYSYLKA
CALL ZATRZYMANIE

CALL CZYSZCZENIE
CALL DLUGI_KOMUNIKAT_2
CALL WYSYLKA
CALL ZATRZYMANIE

CALL CZYSZCZENIE
CALL DLUGI_KOMUNIKAT_3
CALL WYSYLKA
CALL ZATRZYMANIE

CALL CZYSZCZENIE
JMP $ ; KONIEC PROGRAMU

USTAW_CZASOMIERZE:
MOV TMOD, #11H ; TIMER W TRYBIE 16BIT
CLR TF0
CLR TR0
RET

USTAW_LCD:
CLR RS		; CZYSZCZENIE RS UMOZLIWIA WYSLANIE INSTRUKCJI DO WYSWIETLACZA
CLR  D7		
CLR  D6	
SETB D5		
CLR  D4		; WYSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
SETB D7		; NIZSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
CLR D7		
CLR D6		
CLR D5		
CLR D4		; WYSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
SETB D6		
SETB D5		; NIZSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
CLR D7 ; D7	
CLR D6 ; D6		
CLR D5 ; D5		
CLR D4 ; D4		; WYSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
SETB D7		
SETB D6		
SETB D5		
SETB D4		; NIZSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

WYSYLKA_ZNAKU:
MOV C, ACC.7		
MOV D7, C		
MOV C, ACC.6		
MOV D6, C			
MOV C, ACC.5		
MOV D5, C			
MOV C, ACC.4		
MOV D4, C			;  WYZSZA CZWORKA
SETB E			
CLR  E			; ZBOCZE OPADAJACE NA E
MOV C, ACC.3		
MOV D7, C			
MOV C, ACC.2		
MOV D6, C			
MOV C, ACC.1		
MOV D5, C			
MOV C, ACC.0		
MOV D4, C			; NIZSZA CZWORKA
SETB E			
CLR  E			; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE			; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

OPOZNIENIE:
MOV TH0, #0FFH ; 10000H - 40 = FFD5H ; OPOZNIENIE 40US
MOV TL0, #0D5H
SETB TR0
JNB TF0, $
CLR TR0
CLR TF0
RET

OPOZNIENIE_DLUGIE:
MOV TH0, #0ECH ; OPOZNIENIE 5MS
MOV TL0, #078H ; 10000H - 5000 = 0EC78H
SETB TR0
JNB TF0, $
CLR TR0
CLR TF0
RET

ZATRZYMANIE:
MOV A, #200 ; OPOZNIENIE 200 * 5MS = 1S
ASADF:
CALL OPOZNIENIE_DLUGIE
DEC A
JNZ ASADF
RET

CZYSZCZENIE:
CLR RS
CLR D7
CLR D6		
CLR D5		
CLR D4		; WYSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
SETB D4		; NIZSZA CZWORKA
SETB E		
CLR  E		; ZBOCZE OPADAJACE NA E
CALL OPOZNIENIE_DLUGIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

WYSYLKA:
SETB RS		; CZYSZCZENIE RS - UMOZLIWIA WYSYLANIE DANYCH
MOV R1, #30H
PEETLA:
MOV A, @R1		; PRZESYLANIE DO AKUMULATORA ZNAKU WSKAZYWANEGO PRZEZ REJESTR R1
JZ ENDD		; JESLI ZNAK TO ZERO, KONIEC TRANSMISJI
CALL WYSYLKA_ZNAKU	; WYSLIJ ZNAK NA MODUL LCD
INC R1			; ZWIEKSZ WSKAZNIK W CELU WSKAZANIA NA KOLEJNY ZNAK
JMP PEETLA	; POWTORZ
ENDD:
RET

DLUGI_KOMUNIKAT_1:
MOV 30H, #'K' ; PIERWSZA LINIA
MOV 31H, #'O'
MOV 32H, #'M'
MOV 33H, #'U'
MOV 34H, #'N'
MOV 35H, #'I'
MOV 36H, #'K'
MOV 37H, #'A'
MOV 38H, #'T'
MOV 39H, #' '
MOV 3AH, #'N'
MOV 3BH, #'R'
MOV 3CH, #' '
MOV 3DH, #'1'
MOV 3EH, #' '
MOV 3FH, #' '
MOV 58H, #'Q' ; DRUGA LINIA
MOV 59H, #'W'
MOV 5AH, #'E'
MOV 5BH, #'R'
MOV 5CH, #'T'
MOV 5DH, #'Y'
MOV 5EH, #'U'
MOV 5FH, #'I'
MOV 60H, #'O'
MOV 61H, #'P'
MOV 62H, #'A'
MOV 63H, #'S'
MOV 64H, #'D'
MOV 65H, #'F'
MOV 66H, #'G'
MOV 67H, #'H'
MOV 40H, #' ';ZNAKI NIEWIDOCZNE
MOV 41H, #' '
MOV 42H, #' '
MOV 43H, #' '
MOV 44H, #' '
MOV 45H, #' '
MOV 46H, #' '
MOV 47H, #' '
MOV 48H, #' '
MOV 49H, #' '
MOV 4AH, #' '
MOV 4BH, #' '
MOV 4CH, #' '
MOV 4DH, #' '
MOV 4EH, #' '
MOV 4FH, #' '
MOV 50H, #' '
MOV 51H, #' '
MOV 52H, #' '
MOV 53H, #' '
MOV 54H, #' '
MOV 55H, #' '
MOV 56H, #' '
MOV 57H, #' '
MOV 68H, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET

DLUGI_KOMUNIKAT_2:
MOV 30H, #'K'
MOV 31H, #'O'
MOV 32H, #'M'
MOV 33H, #'U'
MOV 34H, #'N'
MOV 35H, #'I'
MOV 36H, #'K'
MOV 37H, #'A'
MOV 38H, #'T'
MOV 39H, #' '
MOV 3AH, #'N'
MOV 3BH, #'R'
MOV 3CH, #' '
MOV 3DH, #'2'
MOV 3EH, #' '
MOV 3FH, #' '
MOV 58H, #'A'
MOV 59H, #'B'
MOV 5AH, #'C'
MOV 5BH, #'D'
MOV 5CH, #'E'
MOV 5DH, #'F'
MOV 5EH, #'G'
MOV 5FH, #'H'
MOV 60H, #'I'
MOV 61H, #'J'
MOV 62H, #'K'
MOV 63H, #'L'
MOV 64H, #'M'
MOV 65H, #'N'
MOV 66H, #'O'
MOV 67H, #'P'
MOV 40H, #' '
MOV 41H, #' '
MOV 42H, #' '
MOV 43H, #' '
MOV 44H, #' '
MOV 45H, #' '
MOV 46H, #' '
MOV 47H, #' '
MOV 48H, #' '
MOV 49H, #' '
MOV 4AH, #' '
MOV 4BH, #' '
MOV 4CH, #' '
MOV 4DH, #' '
MOV 4EH, #' '
MOV 4FH, #' '
MOV 50H, #' '
MOV 51H, #' '
MOV 52H, #' '
MOV 53H, #' '
MOV 54H, #' '
MOV 55H, #' '
MOV 56H, #' '
MOV 57H, #' '

MOV 68H, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET

DLUGI_KOMUNIKAT_3:
MOV 30H, #'K'
MOV 31H, #'O'
MOV 32H, #'M'
MOV 33H, #'U'
MOV 34H, #'N'
MOV 35H, #'I'
MOV 36H, #'K'
MOV 37H, #'A'
MOV 38H, #'T'
MOV 39H, #' '
MOV 3AH, #'N'
MOV 3BH, #'R'
MOV 3CH, #' '
MOV 3DH, #'3'
MOV 3EH, #' '
MOV 3FH, #' '
MOV 58H, #'1'
MOV 59H, #'2'
MOV 5AH, #'3'
MOV 5BH, #'4'
MOV 5CH, #'5'
MOV 5DH, #'6'
MOV 5EH, #'7'
MOV 5FH, #'8'
MOV 60H, #'9'
MOV 61H, #'0'
MOV 62H, #'-'
MOV 63H, #'='
MOV 64H, #'+'
MOV 65H, #'<'
MOV 66H, #'>'
MOV 67H, #']'
MOV 40H, #' '
MOV 41H, #' '
MOV 42H, #' '
MOV 43H, #' '
MOV 44H, #' '
MOV 45H, #' '
MOV 46H, #' '
MOV 47H, #' '
MOV 48H, #' '
MOV 49H, #' '
MOV 4AH, #' '
MOV 4BH, #' '
MOV 4CH, #' '
MOV 4DH, #' '
MOV 4EH, #' '
MOV 4FH, #' '
MOV 50H, #' '
MOV 51H, #' '
MOV 52H, #' '
MOV 53H, #' '
MOV 54H, #' '
MOV 55H, #' '
MOV 56H, #' '
MOV 57H, #' '
MOV 68H, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET
