; Wysyłka szeregowa  3-ch kolejnych komunikatów min 20 znaków na moduł LCD
; Zadaniem jest wyswietlenie trzech komunikatow na module LCD HD44780 dostepnym w symulatorze EDSIM51.
; Ustawienia symulatora:
;  - częstotliwość zegara: 12MHz
;  - częstotliwość odświeżania: 2000x
; 

RS EQU P1.3 ; przypisuje nazwy dla preprocesora
E  EQU P1.2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CALL USTAW_LCD
CALL CZYSZCZENIE_WYSWIETLACZA
CALL WYSWIETL_KOMUNIKAT_1
CALL WRZUC_NA_MODUL
CALL PRZESUWANIE
CALL CZYSZCZENIE_WYSWIETLACZA
CALL WYSWIETL_KOMUNIKAT_2
CALL WRZUC_NA_MODUL
CALL PRZESUWANIE
CALL CZYSZCZENIE_WYSWIETLACZA
CALL WYSWIETL_KOMUNIKAT_3
CALL WRZUC_NA_MODUL
CALL PRZESUWANIE
CALL CZYSZCZENIE_WYSWIETLACZA
call WYSWIETL_KOMUNIKAT_4
JMP $

WRZUC_LITERKE:
	MOV C, ACC.7		
	MOV p1.7, C		
	MOV C, ACC.6		
	MOV p1.6, C			
	MOV C, ACC.5		
	MOV p1.5, C			
	MOV C, ACC.4		
	MOV p1.4, C			;  WYZSZA CZWORKA

	SETB E			
	CLR  E			; ZBOCZE OPADAJACE NA E

	MOV C, ACC.3		
	MOV p1.7, C			
	MOV C, ACC.2		
	MOV p1.6, C			
	MOV C, ACC.1		
	MOV p1.5, C			
	MOV C, ACC.0		
	MOV p1.4, C			; NIZSZA CZWORKA

	SETB E			
	CLR  E			; ZBOCZE OPADAJACE NA E

	CALL OPOZNIENIE_KROTKIE			; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI

OPOZNIENIE_KROTKIE:
	MOV R0, #20
	DJNZ R0, $
RET

OPOZNIENIE_DLUGIE:
	MOV A, #50
	OPOZNIENIE_KROTKIEA:
		CALL OPOZNIENIE_KROTKIE
		DEC A
	JNZ OPOZNIENIE_KROTKIEA
RET

OPOZNIENIE_Z_A:
	MOV A, #16
	OPOZNIENIE_KROTKIED:
		CALL OPOZNIENIE_KROTKIE
		DEC A
	JNZ OPOZNIENIE_KROTKIED
RET

OPOZNIENIE_BARDZO_DLUGIE:
	MOV A, #255
	OPOZNIENIE_KROTKIEB:
		CALL OPOZNIENIE_KROTKIE
		DEC A
	JNZ OPOZNIENIE_KROTKIEB
RET

USTAW_LCD:
		CLR RS		; CZYSZCZENIE RS UMOZLIWIA WYSLANIE INSTRUKCJI DO WYSWIETLACZA
		
		CLR  p1.7		
		CLR  p1.6	
		SETB p1.5		
		CLR  p1.4		; WYSZA CZWORKA
		
			SETB E		
			CLR  E		; ZBOCZE OPADAJACE NA E
		CALL OPOZNIENIE_KROTKIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
		
			SETB E		
			CLR  E		; ZBOCZE OPADAJACE NA E
		SETB p1.7		; NIZSZA CZWORKA
			SETB E		
			CLR  E		; ZBOCZE OPADAJACE NA E
		CALL OPOZNIENIE_KROTKIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI

		CLR p1.7		
		CLR p1.6		
		CLR p1.5		
		CLR p1.4		; WYSZA CZWORKA

		SETB E		
		CLR  E		; ZBOCZE OPADAJACE NA E

		SETB p1.6		
		SETB p1.5		; NIZSZA CZWORKA

		SETB E		
		CLR  E		; ZBOCZE OPADAJACE NA E

		CALL OPOZNIENIE_KROTKIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI

		CLR p1.7		
		CLR p1.6		
		CLR p1.5		
		CLR p1.4		; WYSZA CZWORKA

		SETB E		
		CLR  E		; ZBOCZE OPADAJACE NA E

		SETB p1.7		
		SETB p1.6		
		SETB p1.5		
		SETB p1.4		; NIZSZA CZWORKA

		SETB E		
		CLR  E		; ZBOCZE OPADAJACE NA E

		CALL OPOZNIENIE_KROTKIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

CZYSZCZENIE_WYSWIETLACZA:
	CLR RS

	CLR p1.7
	CLR p1.6		
	CLR p1.5		
	CLR p1.4		; WYSZA CZWORKA

	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	SETB p1.4		; NIZSZA CZWORKA

	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	CALL OPOZNIENIE_DLUGIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

POWROT_KURSORA:
	CLR RS

	CLR p1.7
	CLR p1.6		
	CLR p1.5		
	CLR p1.4		; WYSZA CZWORKA

	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	SETB p1.5		; NIZSZA CZWORKA

	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	CALL OPOZNIENIE_DLUGIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI
RET

PRZESUWANIE:
	MOV R5, #16
	OPOZNIENIE_KROTKIEC:
		CALL OPOZNIENIE_BARDZO_DLUGIE	
		CALL PRZESUN
		DEC R5
		MOV A, R5
	JNZ OPOZNIENIE_KROTKIEC
RET

PRZESUN:
	CLR RS

	CLR p1.7
	CLR p1.6		
	CLR p1.5		
	SETB p1.4		; WYZSZA CZWORKA

	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	SETB p1.7 ; S/C
	CLR p1.6 ; R/L		
	CLR p1.5
	CLR p1.4
	
	SETB E		
	CLR  E		; ZBOCZE OPADAJACE NA E

	CALL OPOZNIENIE_KROTKIE		; OCZEKIWANIE NA WYCZYSZCZENIE FLAGI ZAJETOSCI

RET



WRZUC_NA_MODUL:
		SETB RS		; CZYSZCZENIE RS - UMOZLIWIA WYSYLANIE DANYCH
		MOV R1, #30H
	PEETLA:
		MOV A, @R1		; PRZESYLANIE DO AKUMULATORA ZNAKU WZKAZYWANEGO PRZEZ REJESTR R1
		JZ ENDD		; JESLI ZNAK TO ZERO, KONIEC TRANSMISJI
		CALL WRZUC_LITERKE	; WYSLIJ ZNAK NA MODUL LCD
		INC R1			; ZWIEKSZ WSKAZNIK W CELU WSKAZANIA NA KOLEJNY ZNAK
		JMP PEETLA	; POWTORZ
	ENDD:
RET

WYSWIETL_KOMUNIKAT_1:
	MOV 30H, #'W'
	MOV 31H, #'y'
	MOV 32H, #'s'
	MOV 33H, #'y'
	MOV 34H, #'l'
	MOV 35H, #'k'
	MOV 36H, #'a'
	MOV 37H, #' '
	MOV 38H, #'s'
	MOV 39H, #'z'
	MOV 3AH, #'e'
	MOV 3BH, #'r'
	MOV 3CH, #'e'
	MOV 3DH, #'g'
	MOV 3EH, #'o'
	MOV 3FH, #'w'
	MOV 40H, #'a'
	MOV 41H, #' '
	MOV 42H, #'n'
	MOV 43H, #'a'
	MOV 44H, #' '
	MOV 45h, #'L'
	MOV 46H, #'C'
	MOV 47H, #'D'
	MOV 48H, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET

WYSWIETL_KOMUNIKAT_2:
	MOV 30H, #'W'
	MOV 31H, #' '
	MOV 32H, #'t'
	MOV 33H, #'r'
	MOV 34H, #'y'
	MOV 35H, #'b'
	MOV 36H, #'i'
	MOV 37H, #'e'
	MOV 38H, #' '
	MOV 39H, #'4'
	MOV 3AH, #'-'
	MOV 3BH, #'b'
	MOV 3CH, #'i'
	MOV 3DH, #'t'
	MOV 3EH, #'o'
	MOV 3FH, #'w'
	MOV 40H, #'y'
	MOV 41H, #'m'
	MOV 42H, #' '
	MOV 43H, #'w'
	MOV 44H, #'p'
	MOV 45h, #'r'
	MOV 46H, #'o'
	MOV 47H, #'w'
	MOV 48H, #'a'
	MOV 49H, #'d'
	MOV 4ah, #'z'
	MOV 4bH, #'a'
	MOV 4cH, #'n'
	MOV 4dH, #'i'
	MOV 4eH, #'a'
	MOV 4fH, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET

WYSWIETL_KOMUNIKAT_3:
	MOV 30H, #'W'
	MOV 31H, #'y'
	MOV 32H, #'k'
	MOV 33H, #'o'
	MOV 34H, #'n'
	MOV 35H, #'a'
	MOV 36H, #'l'
	MOV 37H, #' '
	MOV 38H, #'L'
	MOV 39H, #'u'
	MOV 3AH, #'k'
	MOV 3BH, #'a'
	MOV 3CH, #'s'
	MOV 3DH, #'z'
	MOV 3EH, #' '
	MOV 3FH, #'K'
	MOV 40H, #'u'
	MOV 41H, #'s'
	MOV 42H, #'t'
	MOV 43H, #'o'
	MOV 44H, #'w'
	MOV 45h, #'s'
	MOV 46H, #'k'
	MOV 47H, #'i'
	MOV 48H, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET

WYSWIETL_KOMUNIKAT_4:
	MOV 30H, #'K'
	MOV 31H, #'o'
	MOV 32H, #'n'
	MOV 33H, #'i'
	MOV 34H, #'e'
	MOV 35H, #'c'
	MOV 36H, #' '
	MOV 37H, #'p'
	MOV 38H, #'r'
	MOV 39H, #'o'
	MOV 3AH, #'g'
	MOV 3BH, #'r'
	MOV 3CH, #'a'
	MOV 3DH, #'m'
	MOV 3EH, #'u'
	MOV 3FH, #0 ; KONIEC DANYCH DO WYSWIETLANIA
RET
